version: '3'

services:
    backend:
        build: .
        ports:
            -   "8080:8080"
        env_file: .env
        depends_on:
            -   db

    db:
        image: postgres:16.4
        ports:
            -   "5432:5432"
        env_file: .env
        volumes:
            - postgres_data:/var/lib/postgresql/data
volumes:
    postgres_data: